### PR TITLE
Improve TypeScript definition

### PR DESCRIPTION
**Pull request by uwolfer**
- all properties are optional
- export props interface
- mark private things as private

### CODE REVIEW

**Comment by mozmorris** [comment]
Thanks for this @uwolfer but I'm not convinced this is quite right. You've introduced non-null assertions where they're not needed. eg `onUserMediaError` will always have a value.

I'd say we're okay to leave this as is unless of course you've come across a problem consuming the library in a TS project. We're using it in a TS project ourselves and haven't had any issues.

**Comment by uwolfer** [comment]
> Thanks for this @uwolfer but I'm not convinced this is quite right. You've introduced non-null assertions where they're not needed. eg `onUserMediaError` will always have a value.
> 
> I'd say we're okay to leave this as is unless of course you've come across a problem consuming the library in a TS project. We're using it in a TS project ourselves and haven't had any issues.

I think I've seen an IntelliJ IDE warning because of props which are not marked as optional, but I cannot reproduce it right now. It looks like the `defaultProps` implicitly mark props as optional when available. I still think marking optional props explicitly as optional is nice, but probably not required (other examples I've checked do it also, see for example https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L56). Also, in most cases I've checked, the Props interface is exported.

I think the non-null assert is fine because it is always initialized with `defaultProps` when not passed as prop (but it is required when the prop is marked as optional, see this: https://medium.com/@martin_hotell/react-typescript-and-defaultprops-dilemma-ca7f81c661c7). If you prefer, I also could add if-null-checks.

In addition to my first change, I've now also properly marked private things.

If you check the generated `react-webcam.d.ts` in `dist`, I think it looks now as I'd expect it.

**Comment by mozmorris** [comment]
Cool, those other changes look good.

Though I feel like you've mistaken an optional interface property for `prop.isRequired`. They are not the same thing. 

The `props.onUserMediaError!` non-null assertions is not required. `onUserMediaError` will always be a function, or error at compile time if a function isn't passed.

**Comment by uwolfer** [comment]
> Though I feel like you've mistaken an optional interface property for prop.isRequired. They are not the same thing.

Are you really sure about that? (I've never defined props with `prop.isRequired` because I always use TS interfaces for that). And in this component, you do also not use `isRequired`, do you? I'm not sure about it, and I'm happy to learn something new. Do you have any sources / readings about it?

I did just this test: Changed `static defaultProps = {` to `static defaultProps: WebcamProps = {` (which I'm quite sure is a correct change) and did a build. After using the generated .d.ts in my project which is outside of this component, my IntelliJ IDE complains: `Element Webcamx doesn't have required attribute audio`.

> The props.onUserMediaError! non-null assertion is not required. onUserMediaError will always be a function, or error at compile time if a function isn't passed.

If you do not add this assert, you get a TS error (after marking the prop as optional):
`TS2722: Cannot invoke an object which is possibly 'undefined'.`
This is not nice, but the posted link above explains why it is required (and what the alternatives would be).

**Comment by mozmorris** [comment]
Think about what's going on under the hood when the constructor is invoked. React passes in all the consumer props merged with the default props. So for example `onUserMediaError` isn't "optional" from constructors point of view; a function will always be passed. By adding the `?` the component now thinks that `onUserMediaError` could be undefined when that's not actually the case.

**Comment by mozmorris** [comment]
Btw, I'm all up for improving the typings and this change it great. But having to tell the compiler a value isn't null when this should be inferred feels wrong.

**Comment by uwolfer** [comment]
> Think about what's going on under the hood when the constructor is invoked. React passes in all the consumer props merged with the default props. So for example `onUserMediaError` isn't "optional" from constructors point of view; a function will always be passed. By adding the `?` the component now thinks that `onUserMediaError` could be undefined when that's not actually the case.

Yes, this is what in the impl happens. My fix just tries to optimize the generated `react-webcam.d.ts` dist artifact which is the only (I think so) artifact which is used by IDEs when you use this component in another project.

> Btw, I'm all up for improving the typings and this change it great. But having to tell the compiler a value isn't null when this should be inferred feels wrong.

Yes, I agree this is not nice. What's about marking  `onUserMedia` and `onUserMediaError` as optional, remove the two empty functions from `defaultProps` and add a proper null-check around the function calls?

**Comment by mozmorris** [comment]
That sounds good to me tbf 👍 

With the currently published type definitions this is what I see: 
`react-webcam 4.1.0, typescript 3.7.2, react 16.12.0`



Others in our team also use Webstorm yet they've haven't reported any issues using this component as is.

**Comment by mozmorris** [comment]
Thinking about this, I know we all have our IDEs set to use the latest version of TypeScript - I wonder if you're seeing an issue in an older version?

**Comment by uwolfer** [comment]
> That sounds good to me tbf

Updated, please take a look.

> Others in our team also use Webstorm yet they haven't reported any issues using this component as is.

With the currently published version, I also was not able to reproduce any issues (anymore). But after "fixing" the `defaultProps` (specifying the type), the generated output of `react-webcam.d.ts` looks different and I get the error from above in IntelliJ (using TS 3.6.2 & 3.7.4).

**Comment by uwolfer** [comment]
Okay, wait. Thanks for making me think about it again. I've just found this: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#explicit-types-on-defaultprops

Will update the PR accordingly.

**Comment by uwolfer** [comment]
Updated. I think it looks now a bit more like you have suggested it from the beginning ;)

Looks like the blog post I've linked above is outdated, as things related to `defaultProps` have changed with TS 3.0. They suggest to remove the explicit typing of `defaultProps` and instead not marking props as optional. Thanks for your support @mozmorris!

**Pull request merged**
