### PR TITLE
Using render props to simplify image capture

### PR DESCRIPTION
**Pull request by lucassaid**
Using this approach we can get rid of useRef and useCallback when getting the screenshot

### CODE REVIEW

**Comment by mozmorris** [comment]
Hey @lucassaid - this is great, thank you. Will give it a spin and then look to merge it.

**Comment by Apexal** [comment]
Any update on this? @mozmorris

**Comment by mozmorris** [comment]
Sorry for the delay. I did test this and forgot to leave a note. This requires bumping the minimum React version to 16, which I think is legitimate now that that 18 is in RC status. I'll create a major release with this in.

**Comment by mozmorris** [comment]
@Apexal @lucassaid I've published this under `7.0.0`, currently as the `next` tag. Any chance you could test it? `npm install react-webcam@next`

I've tested here locally with a couple of apps we use, everything looks good.

**Comment by Apexal** [comment]
I'm able to successfully use it in a TypeScript project!

**Comment by mozmorris** [comment]
Yup, same. I'll assign it to the latest tag so it's the default. Thanks for test @Apexal. And many thanks again @lucassaid.

**Pull request merged**
