### PR TITLE
Fix for Chrome ≤ 49.0.2623 - getUserMedia undefined

### PR DESCRIPTION
**Pull request by karanjariwala**
https://stackoverflow.com/questions/37315361/chrome-navigator-mediadevices-getusermedia-is-not-a-function

### CODE REVIEW

**Comment by mozmorris** [comment]
Hi @karanjariwala, thank you for this PR 😄 

Could you let me know the browser you're using so that I can test this properly? Also, the build is currently failing.

Once I know how to test this and the build is fixed, I can review the PR.

**Comment by karanjariwala** [comment]
> Hi @karanjariwala, thank you for this PR 😄
> 
> Could you let me know the browser you're using so that I can test this properly? Also, the build is currently failing.
> 
> Once I know how to test this and the build is fixed, I can review the PR.

Hey sure, The error was "t.mediaDevices.getUserMedia is not a function"
It occurred in Chrome Version: 49.0.2623 and OS Mac OS X 10.6.8.

**Comment by mozmorris** [comment]
@karanjariwala did you see my PR?

**Comment by mozmorris** [comment]
Closing due to inactivity. Feel free to reopen @karanjariwala.

**Pull request closed without merging**
