### PR TITLE
Fix issue where on Safari webcam wont work

### PR DESCRIPTION
**Pull request by JeffersonFilho**
This will fix the issue where on Safira the webcam don't work at all and return 
**Unhandled Promise Rejection: TypeError: Type error. 
createObjectURL - react-webcam.js:217
handleUserMedia - react-webcam.js:217
(anonymous function) - react-webcam.js:157**

Remove Navigator.getUserMedia() which is now deprecated and update to MediaDevices.getUserMedia().

### CODE REVIEW

**Comment by crobinson42** [comment]
@JeffersonFilho I just verified your commit fixes in Safari and no regression in Firefox or Chrome - THANKS!

Please fix merge conflicts so we can get this published!

**Comment by JeffersonFilho** [comment]
@crobinson42  Thanks for having a look, but what merge conflicts? Because for me is saying that my branch has no conflicts with the master branch.

https://i.gyazo.com/0fc6212d1af4a1cad159bd5eca055757.png

**Comment by crobinson42** [comment]
Huh - I could have sworn this said merge conflicts over the weekend?! Haha, sorry!

**Comment by JeffersonFilho** [comment]
Hahaha no worries! 👍

**Comment by lbanner3** [comment]
Is there an eta on when this will be merged? @crobinson42

**Comment by brollin** [comment]
Also very interested in seeing this fixed.  The documentation mentions that `react-webcam` is compatible with Safari 11, but I am having the same issue as described here.

**Comment by mozmorris** [comment]
Thanks @JeffersonFilho 👍

**Comment by mozmorris** [comment]
New version published to npm.

**Comment by JeffersonFilho** [comment]
@mozmorris No worries! 👍

**Comment by marianobrc** [comment]
I see this merged and closed, but I'm still having the same issue in v1.0.4, cammera doesn't work at all in iOS mobile browser, safari or chrome neither. Which version should I use?

Thnx

**Comment by JeffersonFilho** [comment]
@marianobrc Sorry, I just saw this message now! Are you still having issues with it? I will test here and see if I can replicate the issue.

**Pull request merged**
