### PR TITLE
make ref work in typescript

### PR DESCRIPTION
**Pull request by k-yle**
The type definitions for `WebcamProps` extends the `HTMLVideoElement` props, so the types for `ref` were wrong, since they were using the ref from `HTMLVideoElement`. 

I've fixed it, and added a regression test by creating a file that typescript compiles during the test phase. If there are no errors, that means the type definitions are valid. 

The test file is just copy-pasted from the README, since it's a good example of how to use the library.

### CODE REVIEW

**Comment by mozmorris** [comment]
@k-yle thank you for this, looks great. One issue I have noticed is the types are no longer detected (testing using a sample project)

I'm guessing the location of the types has changed.

**Comment by k-yle** [comment]
@mozmorris apologies, that should be fixed now. I've renamed the test file to `.test.tsx` to make it clear that jest should only run files ending in `.test.tsx` (i.e. not the `types.tsx` file)

**Comment by mozmorris** [comment]
Fantastic, thank you @k-yle 👍

**Comment by mozmorris** [comment]
Published in `5.2.2`

**Pull request merged**
